version: 2.1
jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
        name: "End to End Testing"
        command: docker-compose up --exit-code-from ui
workflows:
  build-and-test:
    jobs:
      - build-and-test
