version: 2.1
jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: ls -lah
      # - run: ./scripts/dockerbuild-for-ci.sh
      # - run: docker-compose up --exit-code-from ui
workflows:
  build-and-test:
    jobs:
      - build-and-test
