version: 2.1
jobs:
  working_directory: /root/coinstac
  build-and-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: ./scripts/dockerbuild-for-ci.sh
      - run: docker-compose up --exit-code-from ui
workflows:
  build-and-test:
    jobs:
      - build-and-test
