version: 2.1
jobs:
  build-and-test:
    docker:
     environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: test
     - image: coinstacteam/coinstac-ci
     - image: mongo:4.4.0-bionic
    steps:
      - run: xvfb-run --auto-servernum --server-args='-screen 0, 1600x900x24' npm run test:e2e
