version: 2.1
jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: git clone --depth 1 -b $CIRCLE_BRANCH git@github.com:trendscenter/coinstac.git
      - run: cd coinstac && ./scripts/dockerbuild-for-ci.sh
      - run: cd coinstac && docker-compose up --exit-code-from ui
workflows:
  build-and-test:
    jobs:
      - build-and-test
